//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campaign.Business.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CampaignEntities : DbContext
    {
        public CampaignEntities()
            : base("name=CampaignEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Lga> Lgas { get; set; }
        public virtual DbSet<NewsCategory> NewsCategories { get; set; }
        public virtual DbSet<NewsComment> NewsComments { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<VideoCategory> VideoCategories { get; set; }
        public virtual DbSet<VideoComment> VideoComments { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Advert> Adverts { get; set; }
        public virtual DbSet<PollParticipation> PollParticipations { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<CandidateView> CandidateViews { get; set; }
        public virtual DbSet<NewsView> NewsViews { get; set; }
        public virtual DbSet<VideoView> VideoViews { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<ElectoralOffice> ElectoralOffices { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
    }
}
