//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campaign.Business.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollParticipation
    {
        public string ID { get; set; }
        public string UserId { get; set; }
        public string PollId { get; set; }
        public string SelectedPollAnswerOption { get; set; }
        public string UserEmail { get; set; }
        public System.DateTime ParticipationDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Poll Poll { get; set; }
    }
}
