//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campaign.Business.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoView
    {
        public string ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string Type { get; set; }
        public bool IsPublished { get; set; }
        public int Likes { get; set; }
        public string CategoryID { get; set; }
        public int Dislikes { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> Shared { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
        public Nullable<int> LgaID { get; set; }
        public string Town { get; set; }
        public string PublishedBy { get; set; }
        public Nullable<System.DateTime> PublishedAt { get; set; }
        public string CategoryName { get; set; }
        public string LgaName { get; set; }
        public string CountryName { get; set; }
        public string StateName { get; set; }
        public string ImageSource { get; set; }
        public string ImageUrl { get; set; }
    }
}
