//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campaign.Business.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VideoComment()
        {
            this.VideoComments1 = new HashSet<VideoComment>();
        }
    
        public string ID { get; set; }
        public string VideoID { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public string ParentID { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string postedBy { get; set; }
        public string PostedByUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoComment> VideoComments1 { get; set; }
        public virtual VideoComment VideoComment1 { get; set; }
        public virtual Video Video { get; set; }
    }
}
